/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_example_admin_caipiao33_utils_P2PNative */
const char *DES_KEY = "9d851e52381a2d4b85jguk864lhtgtpo";

#ifndef _Included_com_example_admin_caipiao33_utils_P2PNative
#define _Included_com_example_admin_caipiao33_utils_P2PNative
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_example_admin_caipiao33_utils_P2PNative
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_com_example_admin_caipiao33_utils_P2PNative_encrypt
        (JNIEnv * , jobject, jstring);

/*
 * Class:     com_example_admin_caipiao33_utils_P2PNative
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_com_example_admin_caipiao33_utils_P2PNative_decrypt
        (JNIEnv * , jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
